### ISSUE TITLE
update httpoison to v1

### ISSUE THREAD

**Issue by imerkle** [satom99/coxir#23]
** (Mix) Hex dependency resolution failed, change the version requirements of your dependencies or unlock them (by using mix deps.update or mix deps.unlock). If you are unable to resolve the conflicts you can try overriding with {:dependency, "~> 1.0", override: true}

**Comment by satom99** [comment]
I assume this happens when you add `httposion 1.0` as a dependency to your project.

For that matter, we had #17 to update coxir's httpotion version but there's really nothing we can do because a third-party's dependency requires or specifies `httpotion 0.13`. cc @PurgePJ 

Have you tried overriding, as suggested by the error message?
I.e. `{:httpotion, "~> 1.0", override: true}`.
